// <auto-generated />
using AlumniManagement.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlumniManagement.Server.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250424200530_adddata")]
    partial class adddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlumniManagement.Server.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CurrentJobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraduationSemester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraduationYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LookingForMentor")
                        .HasColumnType("bit");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CurrentJobTitle = "QA Engineer",
                            Email = "zmarshall@gmail.com",
                            FirstName = "Zaros",
                            GithubProfile = "zmarsh01",
                            GraduationSemester = "Spring",
                            GraduationYear = "2020",
                            LastName = "Marshall",
                            LinkedInProfile = "ZarosMarshall",
                            LookingForMentor = true,
                            Organization = "Pet Smart",
                            Password = "",
                            PhoneNumber = "000-000-0000",
                            ProfileImage = "",
                            UserType = 2
                        },
                        new
                        {
                            ID = 2,
                            CurrentJobTitle = "Software Engineer",
                            Email = "osamson@gmail.com",
                            FirstName = "Olivia",
                            GithubProfile = "osams02",
                            GraduationSemester = "Fall",
                            GraduationYear = "2021",
                            LastName = "Samson",
                            LinkedInProfile = "OliviaMarshall",
                            LookingForMentor = true,
                            Organization = "Bee Inc.",
                            Password = "",
                            PhoneNumber = "111-111-1111",
                            ProfileImage = "",
                            UserType = 2
                        },
                        new
                        {
                            ID = 3,
                            CurrentJobTitle = "College Administrator",
                            Email = "rtyler@gmail.com",
                            FirstName = "Rose",
                            GithubProfile = "rtyler78",
                            GraduationSemester = "Summer",
                            GraduationYear = "1998",
                            LastName = "Tyler",
                            LinkedInProfile = "RoseTyler",
                            LookingForMentor = false,
                            Organization = "Augusta Technical College",
                            Password = "",
                            PhoneNumber = "222-222-2222",
                            ProfileImage = "",
                            UserType = 0
                        },
                        new
                        {
                            ID = 4,
                            CurrentJobTitle = "College Administrator",
                            Email = "apond@gmail.com",
                            FirstName = "Amy",
                            GithubProfile = "apond55",
                            GraduationSemester = "WInter",
                            GraduationYear = "1999",
                            LastName = "Pond",
                            LinkedInProfile = "AmyPond",
                            LookingForMentor = false,
                            Organization = "Augusta Technical College",
                            Password = "",
                            PhoneNumber = "444-444-4444",
                            ProfileImage = "",
                            UserType = 0
                        },
                        new
                        {
                            ID = 5,
                            CurrentJobTitle = "Scrum Master",
                            Email = "msantos@gmail.com",
                            FirstName = "Maria",
                            GithubProfile = "msantos8",
                            GraduationSemester = "Spring",
                            GraduationYear = "2010",
                            LastName = "Santos",
                            LinkedInProfile = "MariaSantos",
                            LookingForMentor = false,
                            Organization = "Orange.Inc",
                            Password = "",
                            PhoneNumber = "555-555-5555",
                            ProfileImage = "",
                            UserType = 1
                        },
                        new
                        {
                            ID = 6,
                            CurrentJobTitle = "Project Mnager",
                            Email = "jcruz@gmail.com",
                            FirstName = "Jose",
                            GithubProfile = "jcruz11",
                            GraduationSemester = "Fall",
                            GraduationYear = "2011",
                            LastName = "Cruz",
                            LinkedInProfile = "JoseCruz",
                            LookingForMentor = false,
                            Organization = "Text.Inc",
                            Password = "",
                            PhoneNumber = "777-777-7777",
                            ProfileImage = "",
                            UserType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
